### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#33]
I know, it is duplicate, but I really like a list where I can see how far we are.

- [x] Settings
- [X] Calculate season stuff
- [X] Adjust day/night length #23 
- [x] Disable working on land in winter #10 
- [x] Disable missions in winter
- [x] Apply new weather system
- [x] New maintenance system #9 
  - [x] Repair when near shop
  - [x] Change maintenance costs
  - [x] Up the sell price
  - [x] (Change the lease pricing)
- [x] Adjust wages of hired workers
- [X] Add localisation
- [X] Up the height of the loan cap and interest
- [x] Settings GUI
  - [x] Fix missions - Adjust the useFieldMission field daily.
  - [x] Fix missions - Set some state value of the fieldDefs so the game is confused and does not do stuff when it shouldnt
  - [x] Set season length
- [x] Wither crops in winter #28 
- [x] Make it all work in multiplayer
- [x] Allow changing the season length
- [x] Growth Manager canPlantData GUI
  - [x] Improve growth simulation to take into account cut and wither
  - [x] Build GUI and link with canPlantData
  - [x] Implement months
- [x] Growth Manager
  - [x] Implement check if saveGame exists and seasons is new, then ask if growth should be reset
  - [x] Fix fertilising issue
  - [x] Performance Improvements #51
  - [x] Config load and save #49
  - [x] Use growthStateChanged #50
  - [x] Move growthData to an XML file #53
  - [x] Allow growthData to be loaded from map mod. If none, then use growth.xml
  - [x] Improve mod map growthData loading - not full xml file
  - [x] Impact on normal trees #54
  - [x] Changes required for missions based on what can be planted
  - [x] Implement removeUngerminatedSeedsBeforeGrowth - only on > easy difficulty
  - [x] Refactor to use mrbear's improved scanner and helper function #55 
  - [x] Double check growth for potatoes/sugarbeet - potential issues
  - [x] Add default growth data for non standard fruits #52
- [x] FoliageLayer replacements for modmaps.
- [x] Object visibility be season for modmaps.
- [x] Fix multiplayer
- [x] Change animals feed and manure to be season length based
- [x] Implement seasonLengthChanged listener
- [x] Read weather data from custom maps
- [ ] Art assets needed
  - [x] Finish the set of replacement Art assets for winter season.
  - [x] Icon for Snow filltype
  - [ ] Particle system for Snow
  - [ ] Texture for snowmask areas in editor
  - [x] Autumn textures for Poplar (Tree)
  - [x] Winter textures for Oak, Maple and Popplar (Tree)
  - [x] Improved winter LOD texture for Birch
  - [x] Mod icon
- [x] WM
  - [x] get hail back in
  - [x] longer fog in the wet seasons

**Comment by reallogger** [comment]
- [ ] Include power degradation
   - [ ] Lower speed limit
   - [ ] Lower power
   - [ ] Higher fuel consumption

**Comment by joskuijpers** [comment]
V2:

- [ ] Crop prices trend changes per season

**Comment by theSeb1979** [comment]
Wither crops in winter  - done
Please add Growth Manager  as a high level topic. 
Then below it

Performance Improvements https://github.com/RealismusModding/FS17_seasons/issues/51

Config load and save https://github.com/RealismusModding/FS17_seasons/issues/49

Use growthStateChanged https://github.com/RealismusModding/FS17_seasons/issues/50

Move growthData to an XML file https://github.com/RealismusModding/FS17_seasons/issues/53

Impact on normal trees https://github.com/RealismusModding/FS17_seasons/issues/54

Add default growth data for non standard fruits https://github.com/RealismusModding/FS17_seasons/issues/52   (maybe this should be V2? I don't see it real priority for this)

**Comment by joskuijpers** [comment]
Closing. It is useless: all open v1 points have issues, and the v2 already has changed.
